import {
  MdRestaurant,
  MdHotel,
  MdSpa,
  MdHome,
  MdFavorite,
  MdSchool,
  MdLocalHospital,
  MdConstruction,
  MdPets,
  MdBed,
  MdRealEstateAgent,
  MdLocalPharmacy,
  MdFitnessCenter,
  MdAttachMoney,
  MdEvent,
  MdDirectionsCar,
  MdLocalShipping,
  MdDeliveryDining,
  MdPhoneAndroid,
  MdContentCut,
  MdShoppingCart,
  MdCheckroom,
} from "react-icons/md";
import { FaTooth, FaHandHoldingUsd } from "react-icons/fa";

export const categoryIcons = {
  Restaurant: <MdRestaurant className="text-orange-600" />,
  Hotels: <MdHotel className="text-blue-600" />,
  "Beauty Spa": <MdSpa className="text-purple-600" />,
  "Home Decor": <MdHome className="text-teal-600" />,
  "Wedding Planning": <MdFavorite className="text-pink-600" />,
  Education: <MdSchool className="text-indigo-600" />,
  "Rent & Hire": <FaHandHoldingUsd className="text-cyan-600" />,
  Hospitals: <MdLocalHospital className="text-red-600" />,
  Contractors: <MdConstruction className="text-yellow-600" />,
  "Pet Shops": <MdPets className="text-purple-500" />,
  "PG/Hostels": <MdBed className="text-teal-500" />,
  "Estate Agent": <MdRealEstateAgent className="text-purple-700" />,
  Dentists: <FaTooth className="text-cyan-500" />,
  Gym: <MdFitnessCenter className="text-orange-500" />,
  Loans: <MdAttachMoney className="text-green-600" />,
  "Event Organisers": <MdEvent className="text-amber-600" />,
  "Driving Schools": <MdDirectionsCar className="text-blue-500" />,
  "Packers & Movers": <MdLocalShipping className="text-orange-600" />,
  "Courier Service": <MdDeliveryDining className="text-red-500" />,
  Electronics: <MdPhoneAndroid className="text-blue-600" />,
  Salon: <MdContentCut className="text-pink-600" />,
  Grocery: <MdShoppingCart className="text-green-600" />,
  Pharmacy: <MdLocalPharmacy className="text-teal-600" />,
  Clothing: <MdCheckroom className="text-purple-600" />,
};
